### ISSUE TITLE
Why is the layout this way?

### ISSUE THREAD

**Issue by JingoJammer** [sergiocastell/spotify-dogfood#28] opened 2017-12-04 18:19 UTC
![image](https://user-images.githubusercontent.com/34248410/33568787-4778291c-d8ed-11e7-9a84-0d7493167ef5.png)

It's hard to get to some menus with it being this way.

**Comment by sergiocastell** [comment] 2017-12-04 18:21
Dupe of #25. Closed.

**Closed by sergiocastell** 2017-12-04 18:21 UTC
