### ISSUE TITLE
New UI is not user friendly and is waste of space.

### ISSUE THREAD

**Issue by mithuns12** [sergiocastell/spotify-dogfood#26] opened 2017-12-04 09:38 UTC
Hard to change the sort feature, missing song information etc.
Please change it back or provide an option in settings.

**Comment by sergiocastell** [comment] 2017-12-04 18:21
Dupe of #25. Closed.

**Comment by sergiocastell** [comment] 2017-12-06 22:14
Issue #25 fricking disappeared from the repo (?????), so I'm reopening this one until GitHub solves it.

**Comment by sergiocastell** [comment] 2017-12-07 01:21
Issue closed as it has reached it's milestone on version 8.4.31.723. Check it out [here](https://github.com/sergiocastell/spotify-dogfood/releases/tag/8.4.31.723).

**Closed by sergiocastell** 2017-12-07 01:21 UTC
Labels: bug
