### ISSUE TITLE
Randomly stops playing music

### ISSUE THREAD

**Issue by iAriia** [sergiocastell/spotify-dogfood#13] opened 2017-10-22 22:38 UTC
Hey there, I've been having issues w/ the app for the last few updates. I could be listening to an album, then it would just stop playing music until I would unlock my phone to the app and start playing again. I'm not sure if it's an issue w/ my phone, but the app has worked perfectly until the last update or two. Also, when the music is stopped, if someone calls, it'll start playing music again. Is anyone having any sort of similar issue to this?

**Comment by PoorPocketsMcNewHold** [comment] 2017-10-23 07:33
I got the same similar issues on Android Marshmallow, with a Samsung note 4.
But I thought that this was an issue with my headphones instead.

**Comment by iAriia** [comment] 2017-10-23 16:52
Yeah, I'm on MM as well on an LG G4. I usually play the music through my phone's speaker, so I can't give any input on it being a headphone issue. The bug gets annoying since I have to keep unlocking my phone to continue playing the music.

**Comment by sergiocastell** [comment] 2017-10-23 20:54
I can't reproduce this. However, I'm very confident this has nothing to do with Spotify Dogfood itself, but with Spotify's app. For that reason, the issue will be marked as rejected, but it won't be closed so that people are able to comment if this issue is still happening on newer versions, or if more people just experience it. Hope you understand it.

**Comment by iAriia** [comment] 2017-10-23 22:21
Thanks for the response, Sergio.

**Comment by lokiuox** [comment] 2017-11-06 07:36
Same issue on MM and on N now that I updated my rom. I think it could be some "battery optimization" feature that "freezes" the app while playing, so I'll try turning it off for Spotify from the system's settings.

**Comment by iAriia** [comment] 2017-11-07 03:31
UPDATE: Holy shit, turning off the battery optimizations for the app actually managed to fix this problem for me. Thanks for the suggestion, man!

**Comment by lokiuox** [comment] 2017-11-08 11:46
Tested it for about two hours and had no problems, but can't tell for sure if it worked because on my phone the problem doesn't come up very often. I will let you know if if it happens again.

**Comment by sergiocastell** [comment] 2017-11-09 10:35
Issue seems solved after turning off the battery optimizations. For that reason, it'll be closed but may be reopened if needed.  

Thank you

**Closed by sergiocastell** 2017-11-09 10:35 UTC
Labels: cant reproduce, REJECTED
